Web.WMS/Controllers/PickRule/PickRuleController.cs
using BILWeb.PickRule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WMS.Factory;
using WMS.Web.Filter;

namespace Web.WMS.Controllers.PickRule
{
    [RoleActionFilter(Message = "Basic/PickRule")]
    public class PickRuleController : BaseController<T_PickRuleInfo>
    {
        // GET: PickRule
        private IPickRuleService pickRuleService;
        public PickRuleController()
        {
            pickRuleService = (IPickRuleService)ServiceFactory.CreateObject("PickRule.T_PickRule_Func");
            baseservice = pickRuleService;
        }

    }
}

Web.WMS/Views/PickRule/GetModel.cshtml
@using Web.WMS.Common;
@model BILWeb.PickRule.T_PickRuleInfo

@{
    ViewBag.Title = "拣货分配规则";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var strMsg = (string)ViewData["strMsg"];
}

@using (Html.BeginForm("Add", "SystemSet"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    <table style="width:100%;margin:auto;" class="table table-bordered table-striped ">
        <tr>
            <td style="width:50%">
                <div class="form-group">
                    @Html.LabelFor(model => model.MaterialClassName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("MaterialClassCode", Commom.GetList("cbxMaterialClass") as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MaterialClassCode, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    @Html.LabelFor(model => model.PickRuleName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("PickRuleCode", Commom.GetList("cbxPickRule") as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PickRuleCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StrStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Status", Commom.GetList("cbxWarehouseStatus") as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10" style="width:50%">
                        @Html.EditorFor(model => model.PickRuleName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PickRuleName, "", new { @class = "text-danger" })
                    </div>
                </div>
            </td>
        </tr>
    </table>

    <div class="form-group  col-md-10" style="padding-top:35px;">
        <div class="col-md-offset-1 col-md-10">
            <input id="form1" type="submit" value="提 交" class="btn btn-primary pull-left" style="width:100px" />
        </div>
    </div>
</div>
}

@{Html.RenderAction("ErrorMsg", strMsg);}

Web.WMS/Views/PickRule/GetModelList.cshtml
@using BILBasic.Common;
@using BILWeb.PickRule;
@model T_PickRuleInfo
@{
    ViewBag.Title = "拣货规则总览";
    Layout = "~/Views/Shared/_Layout.cshtml";
    PageData<T_PickRuleInfo> pageData = (PageData<T_PickRuleInfo>)ViewData["PageData"];
}

<body class="skin-blue">
    @{Html.RenderPartial("~/Views/Shared/_ViewButtom.cshtml");}
    <div class="box">
        <form action="/PickRule/GetModelList" class="text-right" method="post">
            <div class="box-header">
                <div class="box-tools">
                    <div class="input-group" style="float: right">
                        <label>物料类别：@Html.EditorFor(model => model.MaterialClassCode, new { htmlAttributes = new { @class = "input-sm pull-right" } })</label>
                        <label>规则名称：@Html.EditorFor(model => model.PickRuleName, new { htmlAttributes = new { @class = "input-sm  pull-right" } })</label>
                        <button type="submit" class="btn btn-primary">搜索</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- /.box-header -->
        <div class="box-body table-responsive">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(model => model.MaterialClassCode)</th>
                        <th>@Html.DisplayNameFor(model => model.MaterialClassName)</th>
                        <th>@Html.DisplayNameFor(model => model.PickRuleName)</th>
                        <th>@Html.DisplayNameFor(model => model.StrStatus)</th>
                        <th>@Html.DisplayNameFor(model => model.Creater)</th>
                        <th>@Html.DisplayNameFor(model => model.CreateTime)</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        if (pageData.data != null)
                        {
                            foreach (T_PickRuleInfo row in pageData.data)
                            {
                                <tr>
                                    <td> @row.MaterialClassCode </td>
                                    <td> @row.MaterialClassName </td>
                                    <td> @row.PickRuleName </td>
                                    <td> @row.StrStatus </td>
                                    <td> @row.Creater </td>
                                    <td> @row.CreateTime </td>
                                    <td>@Html.ActionLink("编辑", "getmodel", "PickRule", new { ID = row.ID }, null)</td>
                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="6" align="center"><b>无查询数据</b></td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
            @{Html.RenderAction("PageView", pageData);}
        </div>
    </div>

</body>
<script src="~/Content/SCG/js/Common/Operate.js"></script>