Web.WMS/Controllers/OutStock/OutStockQueryController.cs
using BILBasic.Common;
using BILWeb.Login.User;
using BILWeb.OutStock;
using BILWeb.OutStockCreate;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WMS.Factory;
using WMS.Web.Filter;

namespace Web.WMS.Controllers
{
    [RoleActionFilter(Message = "OutStockQuery/OutStockQuery")]
    public class OutStockQueryController :  BaseController<T_OutStockInfo>
    {
        private IOutStockService outStockService;
        //UserInfo currentUser = Common.Commom.ReadUserInfo();
        public OutStockQueryController()
        {
            outStockService = (IOutStockService)ServiceFactory.CreateObject("OutStock.T_OutStock_Func");
            baseservice = outStockService;
        }

        T_OutStockDetail_Func tfunc_detail = new T_OutStockDetail_Func();
        
        public JsonResult GetDetail(Int32 ID)
        {
            List<T_OutStockDetailInfo> modelList = new List<T_OutStockDetailInfo>();
            string strError = "";
            tfunc_detail.GetModelListByHeaderID(ref modelList, ID, ref strError);
            return Json(modelList, JsonRequestBehavior.AllowGet);
        }



        public JsonResult Sync(string ErpVoucherNo)
        {
            T_OutStock_Func func = new T_OutStock_Func();
            if (func.GetOutStockNoIsExists(ErpVoucherNo) > 0)
            {
                return Json(new { state = false, obj = "该ERP单号已经存在" }, JsonRequestBehavior.AllowGet);
            }

            string ErrorMsg = ""; int WmsVoucherType = -1; string syncType = "ERP"; int syncExcelVouType = -1; DataSet excelds = null;
            BILWeb.SyncService.ParamaterField_Func PFunc = new BILWeb.SyncService.ParamaterField_Func();
            //20:出库单据
            if (PFunc.Sync(20, string.Empty, ErpVoucherNo, WmsVoucherType, ref ErrorMsg, syncType, syncExcelVouType, excelds))
            {

                return Json(new { state = true }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { state = false, obj = ErrorMsg }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult AddBySqlForXT(T_OutStockInfo modeladd)
        {
            string strMsg = "";
            if (baseservice.SaveModelBySqlToDB(currentUser, ref modeladd, ref strMsg))
            {
                //return RedirectToRoute("/outstockquery/getmodellist?VoucherType=24");
                Response.Redirect("/outstockquery/getmodellist?VoucherType=24");
                return View();
            }
            else
            {
                this.TempData["modeladd"] = modeladd;
                return RedirectToAction("GetModel", new { model = modeladd, strMsg = strMsg });
            }
        }

        public FileResult Excel(T_OutStockInfo model)
        {
            string strErrMsg = string.Empty;
            List<T_OutStockInfo> lstExport = new List<T_OutStockInfo>();
            string strError = "";
            DividPage page = new DividPage
            {
                CurrentPageShowCounts = 1000000
            };
            outStockService.GetModelListByPage(ref lstExport, currentUser, model, ref page, ref strError);
            //创建Excel文件的对象
            NPOI.HSSF.UserModel.HSSFWorkbook book = new NPOI.HSSF.UserModel.HSSFWorkbook();
            //添加一个sheet
            NPOI.SS.UserModel.ISheet sheet1 = book.CreateSheet("Sheet1");
            //给sheet1添加第一行的头部标题
            NPOI.SS.UserModel.IRow row1 = sheet1.CreateRow(0);
            row1.CreateCell(0).SetCellValue("单据号");
            row1.CreateCell(1).SetCellValue("据点名");
            row1.CreateCell(2).SetCellValue("效期");
            row1.CreateCell(3).SetCellValue("ERP单号");
            row1.CreateCell(4).SetCellValue("单据类型");
            row1.CreateCell(5).SetCellValue("状态");
            row1.CreateCell(6).SetCellValue("部门");
            row1.CreateCell(7).SetCellValue("创建人");
            row1.CreateCell(8).SetCellValue("创建时间");
            row1.CreateCell(9).SetCellValue("提交时间");
            row1.CreateCell(10).SetCellValue("供应商");
            row1.CreateCell(11).SetCellValue("电话");
            row1.CreateCell(12).SetCellValue("联系人");
            row1.CreateCell(13).SetCellValue("发货地址");
            row1.CreateCell(14).SetCellValue("物流地址");
            row1.CreateCell(15).SetCellValue("等通知发货");
            row1.CreateCell(16).SetCellValue("等外调/等单"); 
            row1.CreateCell(17).SetCellValue("交易条件");
            row1.CreateCell(18).SetCellValue("省");
            row1.CreateCell(19).SetCellValue("市");
            row1.CreateCell(20).SetCellValue("区");
            row1.CreateCell(21).SetCellValue("ERP备注");
            row1.CreateCell(22).SetCellValue("备注");
            row1.CreateCell(23).SetCellValue("客户");
            //将数据逐步写入seet1各个行
            for (int i = 0; i < lstExport.Count; i++)
            {
                NPOI.SS.UserModel.IRow rowtemp = sheet1.CreateRow(i + 1);

                rowtemp.CreateCell(0).SetCellValue(lstExport[i].VoucherNo == null ? "" : lstExport[i].VoucherNo.ToString());
                rowtemp.CreateCell(1).SetCellValue(lstExport[i].StrongHoldName == null ? "" : lstExport[i].StrongHoldName.ToString());
                rowtemp.CreateCell(2).SetCellValue(lstExport[i].EDate == null ? "" : lstExport[i].EDate.ToString());
                rowtemp.CreateCell(3).SetCellValue(lstExport[i].ErpVoucherNo == null ? "" : lstExport[i].ErpVoucherNo.ToString());
                rowtemp.CreateCell(4).SetCellValue(lstExport[i].StrVoucherType == null ? "" : lstExport[i].StrVoucherType.ToString());
                rowtemp.CreateCell(5).SetCellValue(lstExport[i].StrStatus == null ? "" : lstExport[i].StrStatus.ToString());
                rowtemp.CreateCell(6).SetCellValue(lstExport[i].DepartmentName == null ? "" : lstExport[i].DepartmentName.ToString());
                rowtemp.CreateCell(7).SetCellValue(lstExport[i].StrCreater == null ? "" : lstExport[i].StrCreater.ToString());
                rowtemp.CreateCell(8).SetCellValue(lstExport[i].CreateTime.ToString());
                rowtemp.CreateCell(9).SetCellValue(lstExport[i].PostDate.ToString());
                rowtemp.CreateCell(10).SetCellValue(lstExport[i].SupName == null ? "" : lstExport[i].SupName.ToString()); 
                rowtemp.CreateCell(11).SetCellValue(lstExport[i].Phone == null ? "" : lstExport[i].Contact.ToString()); 
                rowtemp.CreateCell(12).SetCellValue(lstExport[i].Contact == null ? "" : lstExport[i].Phone.ToString()); 
                rowtemp.CreateCell(13).SetCellValue(lstExport[i].Address == null ? "" : lstExport[i].Address.ToString()); 
                rowtemp.CreateCell(14).SetCellValue(lstExport[i].Address1 == null ? "" : lstExport[i].Address1.ToString()); 
                rowtemp.CreateCell(15).SetCellValue(lstExport[i].ShipNFlg == null ? "" : lstExport[i].ShipNFlg.ToString()); 
                rowtemp.CreateCell(16).SetCellValue(lstExport[i].ShipWFlg == null ? "" : lstExport[i].ShipWFlg.ToString()); 
                rowtemp.CreateCell(17).SetCellValue(lstExport[i].TradingConditionsName == null ? "" : lstExport[i].TradingConditionsName.ToString());
                rowtemp.CreateCell(18).SetCellValue(lstExport[i].Province == null ? "" : lstExport[i].Province.ToString());
                rowtemp.CreateCell(19).SetCellValue(lstExport[i].City == null ? "" : lstExport[i].City.ToString());
                rowtemp.CreateCell(20).SetCellValue(lstExport[i].Area == null ? "" : lstExport[i].Area.ToString());
                rowtemp.CreateCell(21).SetCellValue(lstExport[i].ERPNote == null ? "" : lstExport[i].ERPNote.ToString());
                rowtemp.CreateCell(22).SetCellValue(lstExport[i].Note == null ? "" : lstExport[i].Note.ToString());
                rowtemp.CreateCell(23).SetCellValue(lstExport[i].CustomerName == null ? "" : lstExport[i].CustomerName.ToString());
            }
            // 写入到客户端 
            System.IO.MemoryStream ms = new System.IO.MemoryStream();
            book.Write(ms);
            ms.Seek(0, SeekOrigin.Begin);
            return File(ms, "application/vnd.ms-excel", DateTime.Now.ToString("yyyyMMddHHmmss") + ".xls");
        }


        //关闭单据
        [HttpPost]
        public JsonResult CloseOutstock(string ID)
        {
            try
            {
                string strError = "";
                T_OutStock_Func tfunc = new T_OutStock_Func();
                if (tfunc.CloseOutStockVoucherNo(Convert.ToInt32(ID),currentUser, ref strError))
                {
                    return Json(new { state = true, obj = strError }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { state = false, obj = strError }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new { state = false, obj = ex.ToString() }, JsonRequestBehavior.AllowGet);
            }

        }

    }
}

Web.WMS/Views/OutStockQuery/GetModel.cshtml
@model BILWeb.OutStock.T_OutStockInfo
@using Web.WMS.Common;
@{
    ViewBag.Title = "单据修改";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var strMsg = (string)ViewData["strMsg"];
}

@using (Html.BeginForm("AddBySqlForXT", "OutStockQuery", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <input name="isDel" value="1" type="hidden" />
        <table id="example1" class="table table-bordered table-striped">
            <tr>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ErpVoucherNo, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ErpVoucherNo, new { htmlAttributes = new { @class = "form-control" }, disabled = "disabled " })
                            @Html.ValidationMessageFor(model => model.ErpVoucherNo, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Province, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Province, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Province, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
                        </div>
                    </div>



                </td>
                <td>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ShipNFlg, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ShipNFlg, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ShipNFlg, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ShipWFlg, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ShipWFlg, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ShipWFlg, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ShipDFlg, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ShipDFlg, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ShipDFlg, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ShipPFlg, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ShipPFlg, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ShipPFlg, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.LabelFor(model => model.TradingConditionsName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.TradingConditionsName, new { htmlAttributes = new { @class = "form-control" } })*@
                            @Html.DropDownList("TradingConditionsName", Commom.GetTradingConditionsNameList as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TradingConditionsName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ERPNote, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ERPNote, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ERPNote, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                <a href="javascript:history.go(-1);" class="btn btn-danger pull-left" style="margin-right:30px;">返回</a>  <input type="submit" value="提 交" class="btn btn-primary pull-left" />
            </div>
        </div>
    </div>
}


@{Html.RenderAction("ErrorMsg", strMsg);}

Web.WMS/Views/OutStockQuery/GetModelList.cshtml
@using BILBasic.Common;
@using Web.WMS.Common;
@using BILWeb.OutStock;
@model T_OutStockInfo
@{
    ViewBag.Title = "出库单据";
    Layout = "~/Views/Shared/_LayoutLayui.cshtml";
    PageData<T_OutStockInfo> pageData = (PageData<T_OutStockInfo>)ViewData["PageData"];
}
<div class="box">
    <div class="layui-card-body layui-table-body layui-table-main">
        <form action="/OutStockQuery/GetModelList" method="post">
            <div class="layui-card-body ">
                <div class="layui-inline layui-show-xs-block">
                    @Html.EditorFor(model => model.CustomerCode, new { htmlAttributes = new { @class = "form-control", @placeholder = "客户" } })
                </div>
                <div class="layui-inline layui-show-xs-block">
                    @Html.EditorFor(model => model.ErpVoucherNo, new { htmlAttributes = new { @class = "form-control", @placeholder = "ERP单号" } })
                </div>
                @*<div class="layui-inline layui-show-xs-block">
            @Html.DropDownList("VoucherType", Commom.GetList("cbxOutStockVoucherName") as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" }, disabled = "disabled" })
        </div>*@
                <div class="layui-inline layui-show-xs-block">
                    @Html.EditorFor(model => model.ToErpWarehouseName, new { htmlAttributes = new { @class = "form-control", @placeholder = "调入仓" } })
                </div>
                <div class="layui-inline layui-show-xs-block">
                    @Html.DropDownList("Status", Commom.GetList("cbxOutstockVoucherStatus") as IEnumerable<SelectListItem>, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="layui-inline layui-show-xs-block">
                    <button type="submit" class="btn btn-primary" lay-submit="" lay-filter="sreach"><i class="layui-icon">&#xe615;</i></button>
                </div>
                @Html.HiddenFor(model => model.VoucherType)
                <input type="hidden" name="PcOrPda" value="1" />
            </div>
        </form>
        @{Html.RenderPartial("~/Views/Shared/_ViewButtom.cshtml");}
        <table class="layui-table layui-form">
            <thead>
                <tr>
                    <th>选择</th>
                    <th>@Html.DisplayNameFor(model => model.VoucherNo)</th>
                    @*<th>@Html.DisplayNameFor(model => model.StrongHoldCode)</th>*@
                    <th>@Html.DisplayNameFor(model => model.StrongHoldName)</th>
                    @*<th>@Html.DisplayNameFor(model => model.CompanyCode)</th>*@
                    <th>@Html.DisplayNameFor(model => model.ErpVoucherNo)</th>
                    <th>@Html.DisplayNameFor(model => model.StrVoucherType)</th>
                    <th>@Html.DisplayNameFor(model => model.StrStatus)</th>
                    @*<th>@Html.DisplayNameFor(model => model.DepartmentName)</th>*@
                    <th>@Html.DisplayNameFor(model => model.StrCreater)</th>
                    <th>@Html.DisplayNameFor(model => model.CreateTime)</th>
                    <th>@Html.DisplayNameFor(model => model.PostDate)</th>
                    @*<th>@Html.DisplayNameFor(model => model.SupName)</th>*@
                    <th>@Html.DisplayNameFor(model => model.ToErpWarehouseName)</th>
                    
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                @{
                    if (pageData.data != null && pageData.data.Count != 0)
                    {
                        foreach (T_OutStockInfo t_OutStockInfo in pageData.data)
                        {
                                <tr>
                                    <td><input type="checkbox" value="@t_OutStockInfo.ID" class="minimal" /></td>
                                    <td>@t_OutStockInfo.VoucherNo</td>
                                    @*<td>@t_OutStockInfo.StrongHoldCode</td>*@
                                    <td>@t_OutStockInfo.StrongHoldName</td>
                                    @*<td>@t_OutStockInfo.CompanyCode</td>*@
                                    <td>@t_OutStockInfo.ErpVoucherNo</td>
                                    <td>@t_OutStockInfo.StrVoucherType</td>
                                    <td>@t_OutStockInfo.StrStatus</td>
                                    @*<td>@t_OutStockInfo.DepartmentName</td>*@
                                    <td>@t_OutStockInfo.StrCreater</td>
                                    <td>@t_OutStockInfo.CreateTime</td>
                                    <td>@t_OutStockInfo.PostDate</td>
                                    @*<td>@t_OutStockInfo.SupName</td>*@
                                    <td>@t_OutStockInfo.ToErpWarehouseName</td>
                                    <td>
                                        <a title="查看" onclick="getDetail(@t_OutStockInfo.ID)" class="detail" data-toggle="modal" data-target="#compose-modal">
                                            <i class="layui-icon">&#xe63c;</i>
                                        </a>
                                        @{ if (t_OutStockInfo.VoucherType == 24)
                                            {<a title="编辑" href="/outstockquery/getmodel?ID=@t_OutStockInfo.ID">
                                                    <i class="layui-icon">&#xe642;</i>
                                                </a> }
                                        }


                                    </td>
                                </tr>


                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="13" align="center"><b>无查询数据</b></td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        @{Html.RenderAction("PageView", pageData);}
    </div>
</div>

<div class="modal fade" id="compose-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" style="width:90%;">
        <div class="modal-content">
            <form action="#" method="post">
                <div class="modal-body">
                    <div class="form-group">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>项次</th>
                                    <th>项序</th>
                                    <th>据点</th>
                                    <th>物料编号</th>
                                    <th>物料描述</th>
                                    <th>批次</th>
                                    <th>订单数量</th>
                                    <th>仓库</th>
                                </tr>
                            </thead>
                            <tbody id="detailTable"></tbody>
                        </table>
                    </div>
                </div>
                <div class="modal-footer clearfix">
                    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times"></i> 关闭</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="~/Content/SCG/js/Common/Operate.js"></script>
<script src="~/Content/SCG/js/OutStock/OutStock.js"></script>
<script type="text/javascript">
    $(".tongbu").click(function () {
        if ($("#ErpVoucherNo").val() == "") {
            alert("先输入ERP单号！");
            return;
        }
        var index = layer.load(1);
        $.ajax({
            type: "GET",
            url: "Sync?ErpVoucherNo=" + $("#ErpVoucherNo").val(),
            dataType: "json",
            async: false,
            success: function (data) {
                if (data.state) {
                    alert("同步成功！");
                } else {
                    alert(data.obj);
                }
                layer.close(index);
            },
            fail: function () {
                alert("提交失败！");
                layer.close(index);
            },
            complate: function () {
                layer.close(index);
            }

        });
    })


</script>